project:
  type: website
  output-dir: docs

website:
  title: "Francisca Villagra Macías"
  navbar: false

format:
  html:
    theme: cosmo
    css: styles-v5.css
    toc: false
    page-layout: article
    embed-resources: false
    include-in-header: header.html

lang: es
